# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f628386e4c982a4e2266fbe7b5b6620def66f182130c73450300fbe879f513ccba80f6ccf50bd51a5371c535b5824bff549f161b44061852aa2b2609c06335b9

test:
  secret_key_base: 6eac6840c904cf0e57c538074e168e6411f36fe75e9d29774d207832a0b7aff162002e8e2a923f2d1802bc371c06d6827a60ee9fafa0695bf04a5bbc5de5d2da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
